### ISSUE TITLE
fn names, defaults, and data locations, for database-backed packages

### ISSUE THREAD

**Issue by cboettig** [cboettig/taxald#9]
Current behavior: calling the function `create_db()` with no arguments results in a data being installed to a default location of `~/.taxald`.  This default can be changed with an environmental variable, `TAXALD_HOME`, or specified directly by providing a location to the `dbdir` argument of the function.

i.e. `create_db()` has the argument `dbdir` default to:

```r
Sys.getenv("TAXALD_HOME", file.path(path.expand("~"), ".taxald"))
```

### many questions:

- [ ] is `create_db()` a poor function name?  (e.g. other packages might use this same pattern of creating a local database, could lead to name conflict).
- [ ] Is an env var preferable to an option?  (Env vars are often used to set home locations for databases when software installs, often defaulting to user's home directory. But R packages tend to use options for user settings other than generic things like credentials.  Technically this database could be accessed by non-R use, which is maybe a case for using env vars).
- [ ] In this setup,  having a default value for `TAXALD_HOME` is technically a CRAN violation.  Should we just do away with the default and have the function error if users don't set an env var first?  It does make the workflow more cumbersome.  
- [ ] If so, is it worth having a package function to set the env var?  I mean, calling `Sys.getenv("TAXALD_HOME"=path.expand("~/.taxald"))` is easy enough for most users, but it's not a documented function task that way.  Maybe `taxald_home("~/.taxald")` would be preferable?

- [ ] Additional thoughts on naming things?  is `TAXALD_HOME` a good name?
- [ ] ... other related potential issues?  

Note that this same pattern could be followed by packages that don't need a db but memoise calls that download and parse data files (like rfishbase 3.0).

**Comment by noamross** [comment]
I'm not sure if this is the best solution, but I use **rappdirs** and put the database in `user_data_dir()`.   **datastorr*, does the same. This is a CRAN violation, too, one that has been very spottily applied, but the spirit of things is basically that you have to make sure the use knows what is happening.  If its clear that the point of a function is to store things on disk, I think that is is in the spirit, but who knows how enforcement will go.

I have used `options()` rather than an env var to specify the DB location.  I weakly perfer because I think people are more likely to have a user-level `.Renviron`, and it's useful to use `.Rprofile` to set options on a project-specific basis.  I have used this in contexts where someone needed access to the DB but didn't have access to the online location it was downloaded from.   I just copied the database and the person put it in their project folder and set the option in a project-specific `.Rprofile`.  I provide an `export_db()` convenience function that just copies the database, as well.  I think having a `dbdir` argument to functions is helpful, too, esp. cases where perhaps one has two copies of a database and wants to work with both of them in the same session.

I don't like `create_db()` because it is too generic.  I haven't separated database creation and populating, so have used `prefix_db_download()`.  I think `TAXONLD_HOME` or `TAXONLD_DB_HOME` is fine, but also maybe keep it close to the function argument, so `TAXONLD_DBDIR`?

**Comment by cboettig** [comment]
Thanks for all this, super helpful to talk this through and hear what you are doing.

- Re CRAN policy, in my experience, they've gotten a lot more strict about this very recently -- including in vignettes & examples as well as in unit tests.  Haven't figured out quite how they are testing for this (testing the package in a read-only filesystem other than tmp-dir would be one way; I arbitrarily suspect they are doing something simpler like grepping for `"."`, but who knows).  In any event, I'm leaning towards strictly following the policy.

I just changed `db_create()` to package-specific `td_create()` (✔️ good idea about non-conflicting names), and made the `dbdir` argument have no default, so creating the db creates the path.  This feels consistent with other functions that create databases, e.g. `dbplyr::nycflights13_sqlite()`.  As this is just a MonetDBLite db, I don't see the value in separating the creation of the database from populating it.  For taxald, `td_create()` does have options to choose which of the naming authorities (itis, ncbi, etc) should be pulled in, optionally using all of them.  

Behind the scenes, `td_create()` passes the `dbdir` argument to `td_home()`, a helper function that sets this argument as an env var, see:  
https://github.com/cboettig/taxald/blob/68e563ec52963e4ab7e1341f76a0bebb87e01a01/R/td_home.R#L10

This does a few things, including: (1) creates the directory requested if it doesn't exist yet, and (2) stores the path given as `TAXALD_HOME`.  This latter step allows the `td_connect()` function (formerly `connect_db()`) to access the location from the env var.   I think this is necessary, because I want the user-facing query functions to take an optional argument `db = connect_db()`, i.e. a database connection.  Arguably these functions could just take the path instead, and create the connection, but I think it's better to pass the connection directly, so users can choose to work on disk when necessary.  but maybe I'm not thinking about that clearly.  



- Re `options()` vs environ, do you actually to a `.Rprofile` or just instruct the user to do so?  I guess one advantage of `.Rprofile` is that we tend to put secure data in `.Renviron` and `.gitignore` it.  Though on the other hand `TAXALD_DBDIR` path is very likely a non-portable path, so it wouldn't work to have that committed to GitHub and maybe does make more sense as an environ.

**Comment by noamross** [comment]
The transfer-the-db-to-another-user case isn't the most common use case, and I guess one could just as easily set this value to the top of the script.  Yes, generally its a non-portable path (esp. for this case, where we wouldn't commit or share the sqlite db).  

One thing about passing around the connection - I'm still thinking about the best way to take advantage of RStudio's connections pane, but I think to do so, you want the connection to be persistent.  So rather than connecting to the database for every operation, I set up the connection in the package namespace with `.onLoad`, and my DB-calling functions refer to this: https://github.com/ecohealthalliance/eidith/blob/master/R/onload.R

**Comment by cboettig** [comment]
Okay, I think these issues are resolved reasonably well in the current version.  

- Using `rappdirs` default with configurable option seems like a good solution to the CRAN policy on default locations.
- All functions take a `db` argument which defaults to `td_connect()`.  `td_connect()` will first attempt to get an existing connection from a cache environment.  If not found, it will create a connection.  A finalizer will close the connection  `onexit` from R.   (This is basically my lightweight version of RStudio `pool`)

This avoids any onLoad / onAttach side effects, but produces a fast connection.  I can verify performance is far better this way than if I was calling a new connection each time; e.g. `replicate(1000, taxa_tbl())` is way fast instead of just failing.
